//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by udl1config.rc
//
#define IDOK2                           2
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_uDL1CONFIG_DIALOG           102
#define IDR_MAINFRAME                   128
#define IDR_ACCELERATOR_MAINMENU        130
#define IDR_MENU_MAIN                   131
#define IDD_DIALOG_INTERRUPTERSETTINGS  132
#define IDD_DIALOG_SHUNTCALC            133
#define IDD_DIALOG_4T020MA              134
#define IDD_DIALOG_RELAYSELECT          135
#define IDD_DIALOG_FACTORYOVERRIDES     136
#define IDD_DIALOG_FAULTS               137
#define IDD_DIALOG_STATUS               138
#define IDD_DIALOG_BUSYSTATUS           139
#define IDD_DIALOG_CHART                140
#define IDD_DIALOG_SPLITDATAFILES       141
#define IDD_DIALOG_32KHZTEST            143
#define IDD_DIALOG_SDLLOCATIONNOTES     144
#define IDI_PointerPB                   150
#define IDI_ZoomOutPB                   151
#define IDI_ZoomInPB                    152
#define IDI_XZoomPB                     153
#define IDI_XYZoomPB                    154
#define IDI_ZoomAllPB                   155
#define IDC_COMBO_MEASUREMENTTYPE       1000
#define IDC_RADIO_INTERVAL6HRS          1001
#define IDC_RADIO_INTERVAL1DAY          1002
#define IDC_RADIO_INTERVAL2DAYS         1003
#define IDC_RADIO_INTERVAL7DAYS         1004
#define IDC_CHECK_DOORSWALARM           1007
#define IDC_CHECK_DOORSWINVERT          1008
#define IDC_CHECK_ACALARM               1009
#define IDC_CHECK_SLOTDISABLE1          1010
#define IDC_CHECK_SLOTDISABLE2          1011
#define IDC_CHECK_SLOTDISABLE3          1012
#define IDC_CHECK_SLOTDISABLE4          1013
#define IDC_EDIT_LOWLIMIT1              1014
#define IDC_EDIT_LOWLIMIT2              1015
#define IDC_EDIT_LOWLIMIT3              1016
#define IDC_EDIT_LOWLIMIT4              1017
#define IDC_EDIT_HIGHLIMIT1             1018
#define IDC_EDIT_HIGHLIMIT2             1019
#define IDC_EDIT_HIGHLIMIT3             1020
#define IDC_EDIT_HIGHLIMIT4             1021
#define IDC_CHECK_ALARMINTDIS1          1030
#define IDC_CHECK_ALARMINTDIS2          1031
#define IDC_CHECK_ALARMINTDIS3          1032
#define IDC_CHECK_ALARMINTDIS4          1033
#define IDC_EDIT_SCALING1               1034
#define IDC_EDIT_SCALING2               1035
#define IDC_EDIT_SCALING3               1036
#define IDC_EDIT_SCALING4               1037
#define IDC_EDIT_OFFSET1                1038
#define IDC_EDIT_OFFSET2                1039
#define IDC_EDIT_OFFSET3                1040
#define IDC_EDIT_OFFSET4                1041
#define IDC_BUTTON_4TO20CALC1           1042
#define IDC_BUTTON_4TO20CALC2           1043
#define IDC_BUTTON_4TO20CALC3           1044
#define IDC_BUTTON_4TO20CALC4           1045
#define IDC_BUTTON_SHUNTCALC1           1046
#define IDC_BUTTON_SHUNTCALC2           1047
#define IDC_BUTTON_SHUNTCALC3           1048
#define IDC_BUTTON_SHUNTCALC4           1049
#define IDC_EDIT_SLOTREADINGLABEL1      1056
#define IDC_EDIT_SLOTREADINGLABEL2      1057
#define IDC_EDIT_SLOTREADINGLABEL3      1058
#define IDC_EDIT_SLOTREADINGLABEL4      1059
#define IDC_STATIC_SLOTREADINGLABEL5    1060
#define IDC_CHECK_DOORCLOSED            1061
#define IDC_CHECK_ACPRESENT             1062
#define IDC_RICHEDIT_GPSSTATUS          1063
#define IDC_EDIT_LATITUDE               1064
#define IDC_EDIT_LONGITUDE              1065
#define IDC_EDIT_RELAYOPENDWELL         1066
#define IDC_EDIT_RELAYCLOSEDWELL        1067
#define IDC_EDIT_UTCOFFSET              1068
#define IDC_CHECK_ACSYNC                1069
#define IDC_CHECK_RELAYONFIRST          1070
#define IDC_CHECK_RELAYNC               1071
#define IDC_BUTTON_RECTSTATUS           1072
#define IDC_BUTTON_RECTON               1073
#define IDC_BUTTON_CYCLEINT             1074
#define IDC_BUTTON_RECTOFF              1075
#define IDC_BUTTON_COMMSTATUS           1076
#define IDC_BUTTON_TESTTX               1077
#define IDC_BUTTON_COMMSTATUS3          1077
#define IDC_BUTTON_CHARTTEST            1077
#define IDC_BUTTON_CHARTDC              1077
#define IDC_EDIT_RELAYOPENDWELL2        1078
#define IDC_BUTTON_CHARTAC              1078
#define IDC_RADIO_SAT1                  1079
#define IDC_BUTTON_CHARTTEMP            1079
#define IDC_RADIO_SAT2                  1080
#define IDC_BUTTON_CHARTALL             1080
#define IDC_RADIO_SAT3                  1081
#define IDC_BUTTON_CHARTDCWAVE          1081
#define IDC_RADIO_SAT4                  1082
#define IDC_BUTTON_CHARTINT             1082
#define IDC_BUTTON_CHARTINTDC           1082
#define IDC_RADIO_SAT5                  1083
#define IDC_BUTTON_CHARTINTAC           1083
#define IDC_RADIO_GSMBAND1              1084
#define IDC_RADIO_GSMBAND2              1085
#define IDC_COMBO_PORTSEL               1086
#define IDC_EDIT_FIRMVER                1087
#define IDC_EDIT_ESN                    1088
#define IDC_RICHEDIT2_LINKSTATUS        1089
#define IDC_RICHEDIT_CONFIGSTATUS       1090
#define IDC_BUTTON_READFAULTS           1091
#define IDC_BUTTON_DEFAULTS             1092
#define IDC_BUTTON_WRITEFILE            1093
#define IDC_BUTTON_WRITERMU             1094
#define IDC_BUTTON_READRMU              1095
#define IDC_BUTTON_READFILE             1096
#define IDC_BUTTON_UPDATEREADINGS       1097
#define IDC_BUTTON_SETFACTORY           1097
#define IDC_CHECK_4TO20MA1              1098
#define IDC_BUTTON_ANALOGTEST           1098
#define IDC_CHECK_4TO20MA2              1099
#define IDC_BUTTON_CALIBRATE            1099
#define IDC_CHECK_4TO20MA3              1100
#define IDC_BUTTON_SETSERIAL            1100
#define IDC_CHECK_4TO20MA4              1101
#define IDC_BUTTON_SHUNTCALCDC          1101
#define IDC_RICHEDIT2_SLOTREADING1      1102
#define IDC_BUTTON_SHUNTCALCAC          1102
#define IDC_RICHEDIT2_SLOTREADING2      1103
#define IDC_BUTTON_ANALOGTEMPTEST       1103
#define IDC_RICHEDIT2_SLOTREADING3      1104
#define IDC_BUTTON_DLGTEST              1104
#define IDC_RICHEDIT2_SLOTREADING4      1105
#define IDC_BUTTON_32KHZTEST            1105
#define IDC_RICHEDIT2_SLOTREADING5      1106
#define IDC_BUTTON_SDLLOCATIONNOTES     1106
#define IDC_BUTTON_REBOOT               1107
#define IDC_CHECK_LOWLIMENABLE1         1108
#define IDC_BUTTON_SETRTC               1108
#define IDC_CHECK_LOWLIMENABLE2         1109
#define IDC_EDIT_CYCLETIME              1109
#define IDC_BUTTON_EXTRACTDATA          1109
#define IDC_CHECK_LOWLIMENABLE3         1110
#define IDC_EDIT_OFFTIME                1110
#define IDC_BUTTON_CLEARDATA            1110
#define IDC_CHECK_LOWLIMENABLE4         1111
#define IDC_EDIT_DURATION               1111
#define IDC_BUTTON_EXTRACTSDLDATA       1111
#define IDC_CHECK_HIGHLIMENABLE1        1112
#define IDC_EDIT_AMPS                   1112
#define IDC_CHECK_HIGHLIMENABLE2        1113
#define IDC_EDIT_MILLIVOLTS             1113
#define IDC_EDIT_REXT                   1113
#define IDC_CHECK_HIGHLIMENABLE3        1114
#define IDC_EDIT_4MAVALUE               1114
#define IDC_CHECK_HIGHLIMENABLE4        1115
#define IDC_EDIT_20MAVALUE              1115
#define IDC_RICHEDIT_READINGSTATUS      1116
#define IDC_EDIT_IMEI                   1117
#define IDC_EDIT_SIMID                  1118
#define IDC_STATIC_DOOR                 1119
#define IDC_STATIC_AC                   1120
#define IDC_BUTTON_RELAYSELECT          1121
#define IDC_RADIO_SOLIDSTATERELAY       1121
#define IDC_RICHEDIT_GPSSTATUS2         1122
#define IDC_EDIT_BASEFIRMVER            1122
#define IDC_RADIO_MERCURYRELAY          1122
#define IDC_CHECK_NOLIMITALARMS         1122
#define IDC_CHECK_GPS                   1122
#define IDC_EDIT_LATITUDE2              1123
#define IDC_EDIT_BASEESN                1123
#define IDC_CHECK_NOACALARMS            1123
#define IDC_CHECK_LARGEMEM              1123
#define IDC_EDIT_LONGITUDE2             1124
#define IDC_EDIT_FACTORYOVERRIDES       1124
#define IDC_CHECK_NODOORALARMS          1124
#define IDC_CHECK_LARGEMEM2             1124
#define IDC_CHECK_PROTOTYPE             1124
#define IDC_EDIT_RELAYOPENDWELL3        1125
#define IDC_BUTTON_SETOVERRIDES         1125
#define IDC_CHECK_ENABLEDATALOGGER      1125
#define IDC_EDIT_RELAYCLOSEDWELL2       1126
#define IDC_CHECK_LOCKSCHEDULE          1126
#define IDC_BUTTON_EXTRACTDATALOGGER    1126
#define IDC_EDIT_UTCOFFSET2             1127
#define IDC_BUTTON_EXTRACTDATALOGGER2   1127
#define IDC_BUTTON_RESETDATALOGGER      1127
#define IDC_CHECK_ACSYNC2               1128
#define IDC_STATIC_IMEI                 1128
#define IDC_CHECK_RELAYONFIRST2         1129
#define IDC_STATIC_SIMID                1129
#define IDC_CHECK_RELAYNC2              1130
#define IDC_RICHEDIT_RSSI               1130
#define IDC_BUTTON_RECTSTATUS2          1131
#define IDC_STATIC_RSSI                 1131
#define IDC_BUTTON_RECTON2              1132
#define IDC_RICHEDIT_HOSTACK            1132
#define IDC_BUTTON_CYCLEINT2            1133
#define IDC_STATIC_HOSTACK              1133
#define IDC_BUTTON_RECTOFF2             1134
#define IDC_PROGRESS_RSSI               1134
#define IDC_BUTTON_COMMSTATUS2          1135
#define IDC_EDIT1                       1135
#define IDC_EDIT_FAULTS                 1135
#define IDC_EDIT_STATUSTEXT             1135
#define IDC_EDIT_SAMPLECYCLEPERIODHOURS 1135
#define IDC_EDIT_1PPSCOUNT              1135
#define IDC_BUTTON_TESTTX2              1136
#define IDC_EDIT_SCALEFACTORDC          1136
#define IDC_EDIT_MSCOUNT                1136
#define IDC_RADIO_SAT6                  1137
#define IDC_PROGRESS_BUSYDLG            1137
#define IDC_EDIT_OFFSETDC               1137
#define IDC_RADIO_SAT7                  1138
#define IDC_RADIO_RNGLOW                1138
#define IDC_RADIO_SAT8                  1139
#define IDC_RADIO_RNGMED                1139
#define IDC_RADIO_SAT9                  1140
#define IDC_RADIO_RNGHIGH               1140
#define IDC_RADIO_SAT10                 1141
#define IDC_CHECK_DCENABLED             1141
#define IDC_RADIO_GSMBAND3              1142
#define IDC_CHECK_ACENABLED             1142
#define IDC_RADIO_GSMBAND4              1143
#define IDC_EDIT_SCALEFACTORAC          1143
#define IDC_EDIT_RELAYOPENDWELL4        1144
#define IDC_EDIT_OFFSETAC               1144
#define IDC_COMBO_PORTSEL2              1145
#define IDC_PROGRESS_MEMUSE             1145
#define IDC_EDIT_FIRMVER2               1146
#define IDC_STATIC_CAPTION              1146
#define IDC_CHECK_TEMPENABLED           1146
#define IDC_EDIT_ESN2                   1147
#define IDC_EDIT_NOTES                  1147
#define IDC_RICHEDIT_CONFIGSTATUS2      1148
#define IDC_RADIO_TEMPC                 1148
#define IDC_BUTTON_READFAULTS2          1149
#define IDC_EDIT_SAMPLECYCLEPERIODMINS  1149
#define IDC_CHARTVIEWER2                1149
#define IDC_BUTTON_DEFAULTS2            1150
#define IDC_EDIT_SAMPLECYCLEPERIODSECS  1150
#define IDC_BUTTON_WRITEFILE2           1151
#define IDC_RADIO_DCV                   1151
#define IDC_BUTTON_WRITERMU2            1152
#define IDC_RADIO_TEMPF                 1152
#define IDC_BUTTON_READRMU2             1153
#define IDC_RADIO_DCA                   1153
#define IDC_BUTTON_READFILE2            1154
#define IDC_RADIO_ACV                   1154
#define IDC_RICHEDIT2_LINKSTATUS2       1155
#define IDC_RADIO_ACA                   1155
#define IDC_EDIT_IMEI2                  1156
#define IDC_CHARTVIEWER                 1156
#define IDC_EDIT_CHARTTITLE             1156
#define IDC_EDIT_SIMID2                 1157
#define IDC_RADIO_UTC                   1157
#define IDC_BUTTON_REBOOT2              1158
#define IDC_RADIO_LOCAL                 1158
#define IDC_BUTTON_RELAYSELECT2         1159
#define IDC_BUTTON_READDATAFILE         1159
#define IDC_ChartViewer                 1160
#define IDC_BUTTON_SPLITDATAFILE        1160
#define IDC_PointerPB                   1161
#define IDC_EDIT_SAMPLECYCLEDELAYMS     1161
#define IDC_ZoomInPB                    1162
#define IDC_CHECK_TIMEENABLED           1162
#define IDC_ZoomOutPB                   1163
#define IDC_RADIO_TDUTC                 1163
#define IDC_StartDate                   1164
#define IDC_RADIO_TDLOCAL               1164
#define IDC_Duration                    1165
#define IDC_EDIT_SAMPLECYCLEDELAYMS2    1165
#define IDC_EDIT_ACQUISITIONDELAYMINS   1165
#define IDC_XZoomPB                     1166
#define IDC_XYZoomPB                    1167
#define IDC_HScrollBar                  1168
#define IDC_VScrollBar                  1169
#define IDC_BUTTON2                     1171
#define IDC_BUTTON_PRINT                1171
#define IDC_STATIC_ZOOMMODE             1172
#define IDC_BUTTON_SAVECHART            1173
#define IDC_BUTTON_ZOOMALL              1174
#define IDC_BUTTON_PREVWAVE             1175
#define IDC_BUTTON_NEXTWAVE             1176
#define IDC_EDIT_DCWAVEREPINT           1177
#define IDC_BUTTON_FIRSTWAVE            1177
#define IDC_EDIT_DCWAVEDUR              1178
#define IDC_BUTTON_LASTWAVE             1178
#define IDC_CHECK_DCWAVECAPEN           1179
#define IDC_CHECK_DCWAVECAPCONT         1180
#define IDC_BUTTON_SELECTFILES          1180
#define IDC_CHECK_DCWAVEGPSSYNC         1181
#define IDC_BUTTON_CONVERTFILES         1181
#define IDC_EDIT_DCWAVESAMPLERATE       1182
#define IDC_CHECK_INCLUDENOTES          1182
#define IDC_CHECK_NOEXTENDEDGPSSYNC     1183
#define IDC_CHECK_INCLUDEVERBALTIMEDATE 1183
#define IDC_CHECK_INCLUDEEXCELTIME      1184
#define IDC_EDIT_FASTOFFSETMS           1184
#define IDC_CHECK_INCLUDEDCREADINGS     1185
#define IDC_CHECK_SYNCOFFSETENABLE      1185
#define IDC_CHECK_INCLUDEACREADINGS     1186
#define IDC_EDIT_EHPEMIN                1186
#define IDC_CHECK_INCLUDETEMPREADINGS   1187
#define IDC_EDIT_EHPEMINTIMEOUT         1187
#define IDC_CHECK_INCLUDETEMPREADINGS2  1188
#define IDC_CHECK_NOEXTENDEDGPSSYNC2    1188
#define IDC_CHECK_MINEHPEENABLE         1188
#define IDC_CHECK_INCLUDETEMPREADINGS3  1189
#define IDC_LIST_FILELIST               1190
#define IDC_BUTTON_PROGRESSABORT        1191
#define IDC_CHECK_INCLUDEUNITS          1191
#define IDC_STATIC_ADVANCED1            1192
#define IDC_STATIC_ADVANCED2            1193
#define IDC_STATIC_ADVANCED3            1194
#define IDC_STATIC_ADVANCED6            1195
#define IDC_STATIC_ADVANCED7            1196
#define IDC_STATIC_WAVEPRINT            1202
#define IDC_STATIC_ADVANCED4            1203
#define IDC_STATIC_ADVANCED5            1204
#define IDC_STATIC_1SDCDELAY            1205
#define IDC_CHECK_TIMELOCK              1206
#define IDC_STATIC_1SDCDELAY2           1206
#define IDC_STATIC_ACQUISITIONDELAY     1206
#define IDC_CHECK_RTCLOCK               1207
#define IDC_CHECK_SHOWMINMAX            1207
#define IDC_CHECK_SHOWMINMAX2           1208
#define IDC_CHECK_NODECIMATION          1208
#define IDC_BUTTON_BINARYEXTRACT        1208
#define IDC_CHECK_INTTRACKINGENABLE     1209
#define IDC_CHECK_INTTRACKINGONFIRST    1210
#define IDC_EDIT_INTOFFTIME             1211
#define IDC_EDIT_INTONTIME              1212
#define IDC_EDIT_INTONTOOFFOFFSET       1213
#define IDC_EDIT_INTOFFTOONOFFSET       1214
#define IDC_EDIT_INTUTCOFFSET           1215
#define IDC_EDIT_INTCYCLETIME           1216
#define IDC_EDIT_INTCHAINAGE            1217
#define IDC_EDIT_INTSTNSERIES           1218
#define IDC_STATIC_INTRACK1             1219
#define IDC_STATIC_INTRACK2             1220
#define IDC_STATIC_INTRACK3             1221
#define IDC_STATIC_INTRACK4             1222
#define IDC_STATIC_INTRACK5             1223
#define IDC_STATIC_INTRACK6             1224
#define IDC_STATIC_INTRACK7             1225
#define IDC_STATIC_INTRACK8             1226
#define IDC_STATIC_INTRACK9             1227
#define IDC_BUTTON_MEMTIME              1228
#define IDC_BUTTON_DONOTHING            1229
#define IDC_STATIC_SDLSTNSERIES         1230
#define IDC_STATIC_SDLCHAINAGE          1231
#define IDC_EDIT_SDLSTNSERIES           1232
#define IDC_EDIT_SDLCHAINAGE            1233
#define IDC_CHECK_SDLLOCATIONENNOTESABLE 1234
#define ID_FILE_OPEN32772               32772
#define ID_FILE_SAVEAS                  32773
#define ID_FILE_DEFAULTS                32774
#define ID_FILE_EXIT                    32775
#define ID_COMMUNICATIONS_READFROMuDL1  32776
#define ID_COMMUNICATIONS_WRITETOuDL1   32777
#define ID_HELP_CONFIGURATIONGUIDE      32778
#define ID_HELP_BINARYMEMORYEXTRACTIONTOOL 32785
#define ID_HELP_MAXIMUMACQUISITIONTIMEESTIMATE 32786

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        147
#define _APS_NEXT_COMMAND_VALUE         32787
#define _APS_NEXT_CONTROL_VALUE         1229
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
